dist: trusty
os: 
  - linux-ppc64le
sudo: required
language: go
go:
- "1.12.x"
addons:
  apt:
    packages:
      - libsecret-1-dev
      - pass
        
script:
  - cd $GOPATH/src/github.com
  - mkdir docker
  - cd docker
  - git clone https://github.com/docker/docker-credential-helpers.git
  - cd docker-credential-helpers
  - make secretservice
  - make pass
