---
  # See appveyor.yml for windows build.
  os: linux-ppc64le
  sudo: required
  language: go
  dist: trusty
  go:
    - 1.12.x
  addons:
    apt:
      packages:
        - libsecret-1-dev
        - pass
        
   script:
    - go get github.com/docker/docker-credential-helpers
    - cd $GOPATH/docker/docker-credentials-helpers
    - make secretservice
    - make pass
